on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: rhynelabkubereg.azurecr.io
        username: ${{ secrets.acr_rhynelabkubereg_username }}
        password: ${{ secrets.acr_rhynelabkubereg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t rhynelabkubereg.azurecr.io/rhynelabkube1:${{ github.sha }}
        docker push rhynelabkubereg.azurecr.io/rhynelabkube1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_rhynelabkube1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep rhynelab-kube-1b1bb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace rhynelab-kube-1b1bb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: rhynelab-kube-1b1bb
        container-registry-url: rhynelabkubereg.azurecr.io
        container-registry-username: ${{ secrets.acr_rhynelabkubereg_username }}
        container-registry-password: ${{ secrets.acr_rhynelabkubereg_password }}
        secret-name: rhynelabkubedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: rhynelab-kube-1b1bb
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          rhynelabkubereg.azurecr.io/rhynelabkube1:${{ github.sha }}
        imagepullsecrets: |
          rhynelabkubedockerauth